### PR TITLE
Fix #12 SQL Error with Visibility

### LINKED ISSUE #12: SQL Error with Visibility
bug1

bug2

@effone

### PR DESCRIPTION
**Pull request by Sama34**
Fix #12 SQL Error with Visibility

I left the following check out on purpose because users won't be able to see the post content anyways:
https://github.com/mybb/mybb/blob/d2f2e6912c7a98ab4cda116e028856df3ee6902b/showthread.php#L117

### CODE REVIEW

**Comment by effone** [comment]
Thanks for the PR.

**Review by lairdshaw — APPROVED** [review]
This fixes the bug of #12, and although I haven't tested it, the logic of visibility seems correct based on visual inspection. I have one question with a follow-up though: why are we caching pinned posts when we aren't sure the cache will be used in this request? Shouldn't we only cache within this later conditional?:
```php
		if ($post['pid'] == $thread['firstpost'] && $thread['pinned']) {
```
I ask this with the awareness that I might very well be missing something here.

**Comment by Eldenroot** [comment]
This fix works for me on my live board. Ajax is working, so the main issue is solved.

**Comment by lairdshaw** [comment]
> This fix works for me on my live board. Ajax is working, so the main issue is solved.

Yes, the main issue is solved. My question is not directly related to the PR nor to the bug.

**Comment by effone** [comment]
@lairdshaw if you are referring that the cache is not required in other pages as the listing is for the first page only; the reason is we need the cache for every single post throughout the thread just to determine the state of the pin / unpin button for each post, atleast.

**Comment by lairdshaw** [comment]
Thank you, @effone. That explains things perfectly. My question is answered.

**Comment by Eldenroot** [comment]
@Sama34 - thx for your contribution!

**Comment by Sama34** [comment]
@lairdshaw @effone Unrelated, yes, but even so I would suggest you remove the hook if this check fails:
https://github.com/mybbgroup/Pin-Post/blob/f71a62d1bfc096f30bb63ee82489fa7b2ffc5c76/upload/inc/plugins/pinpost.php#L227

There is no point in running the hook multiple times if you know the forum is invalid.

I'd rather add the forum check around the following line and then add the postbit hook if necessary:
https://github.com/mybbgroup/Pin-Post/blob/f71a62d1bfc096f30bb63ee82489fa7b2ffc5c76/upload/inc/plugins/pinpost.php#L193

(I'd pick this line because you are currently running one query even if the forum is invalid.)

**Comment by lairdshaw** [comment]
That makes sense and seems to be a logical change, @Sama34. The only thing I wasn't sure about was your final comment in parentheses: which is the one query that's being run even if the forum is invalid? Again in this conversation, it seems I'm missing something.

**Comment by Sama34** [comment]
The following one:
https://github.com/mybbgroup/Pin-Post/blob/f71a62d1bfc096f30bb63ee82489fa7b2ffc5c76/upload/inc/plugins/pinpost.php#L202

Also, `$thread` is already available at that point. Also the subsequent query, which might be skipped if the forum is invalid.

**Comment by lairdshaw** [comment]
OK, but that's all conditional on the input action being "pin" or "unpin", which is comparatively rare. So, I misinterpreted you - I had thought you were talking about the general case of "showthread.php" with no specific action.

**Pull request merged**
